spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgresdb
    username: postgres
    password: password
    poll-size: 30
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

#app:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/postgresdb
#    username: postgres
#    password: password
#    poll-size: 30

#    database-platform: org.hibernate.dialect.PostgreSQLDialect