server:
  port: 8018
  servlet:
#    session:
#      cookie:
#        secure: true
    context-path: /api/practice

spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/postgresdb
    username: postgres
    password: password
    poll-size: 30
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
#  main:
#    allow-bean-definition-overriding: true

application:
  jwt:
    secretKey: securesecuresecuresecuresecuresecuresecuresecure
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 10